# Generated by Django 6.0 on 2025-12-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('apartment_type', models.CharField(choices=[('ST', 'Studio'), ('1B', '1 Bedroom'), ('2B', '2 Bedrooms'), ('3B', '3 Bedrooms'), ('PH', 'Penthouse')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('square_meters', models.FloatField()),
                ('floor', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
