# Generated by Django 4.2.27 on 2026-01-05 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартири'},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.CharField(help_text='Повна адреса квартири', max_length=255, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartment_type',
            field=models.CharField(choices=[('ST', 'Studio'), ('1B', '1 Bedroom'), ('2B', '2 Bedrooms'), ('3B', '3 Bedrooms'), ('PH', 'Penthouse')], max_length=2, verbose_name='Тип квартири'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(help_text='Детальний опис квартири', verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.IntegerField(help_text='Поверх будинку', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Поверх'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Чи вільна квартира для продажу', verbose_name='Доступна'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Ціна в доларах', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10000000)], verbose_name='Ціна ($)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='square_meters',
            field=models.FloatField(help_text='Площа квартири в квадратних метрах', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)], verbose_name='Площа (м²)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='title',
            field=models.CharField(help_text='Назва/заголовок квартири', max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
    ]
